<?php

/**
 * @file
 * Preprocess functions for the c-ShARP Subtheme.
 */

use Drupal\Core\Menu\MenuTreeParameters;

/**
 * Prepares variables for the html.html.twig template.
 */
function c_sharp_subtheme_preprocess_html(&$variables) {
  $variables['stanford_basic_path'] = \Drupal::service('extension.list.theme')->getPath('stanford_basic');
}

/**
 * Implements hook_theme_suggestions_HOOK_alter().
 */
function c_sharp_subtheme_theme_suggestions_block_alter(array &$suggestions, array $variables) {
  if (!empty($variables['elements']['#id']) && $variables['elements']['#id'] == 'c_sharp_subtheme_search') {
    $suggestions[] = 'block__stanford_basic_search';
  }
}

/**
 * Implements hook_preprocess_HOOK().
 */
function c_sharp_subtheme_preprocess_ds_entity_view(&$variables) {
  // if not running on a paragraph, exit out.
  if (!isset($variables['content']['#paragraph'])) {
    return;
  }

  $paragraph = $variables['content']['#paragraph'];

  // Process Banners
  if ($paragraph->bundle() == 'stanford_banner') {
    c_sharp_subtheme_preprocess_banner($variables);
  }
}

/**
 * Implements hook_preprocess_banner().
 */
function c_sharp_subtheme_preprocess_banner(&$variables) {

  $paragraph = $variables['content']['#paragraph'];

  // Add banner variant style class to card wrapper.
  $variables['attributes']['class'][] = $paragraph->getBehaviorSetting('react_paragraphs:banner_variant_info', 'banner_style');
}

/**
 * Implements hook_preprocess_page_title().
 */
function c_sharp_subtheme_preprocess_page_title(&$variables) {
  if (\Drupal::request()->getPathInfo() == '/search') {
    $variables['title']['#markup'] = 'Search Shared Facilities';
  }
}

function c_sharp_subtheme_preprocess_block(&$variables){
  if ($variables['plugin_id'] == 'system_menu_block:main' && \Drupal::hasService('config_pages.loader')) {
    /** @var \Drupal\config_pages\ConfigPagesLoaderServiceInterface $config_pages */
    $config_pages = \Drupal::service('config_pages.loader');
    $new_menu = (bool) $config_pages->getValue('stanford_basic_site_settings', 'su_site_new_menu', 0, 'value');
    if ($new_menu) {
      $variables['attributes']['data-island'] = 'main-menu-island';
      $variables['#attached']['library'][] = 'stanford_basic/decoupled_menu';
      $menu = \Drupal::menuTree()->load('main', new MenuTreeParameters());
      $variables['#attached']['drupalSettings']['stanford_basic']['decoupledMenuItems'] = _c_sharp_subtheme_get_menu_tree_links($menu);
      $variables['elements']['#cache']['tags'][] = 'stanford_profile_helper:menu_links';
    }
  }
}

function _c_sharp_subtheme_get_menu_tree_links(array $items) {
  $tree = [];
  foreach ($items as $id => $item) {
    if (!$item->link->isEnabled()) {
      continue;
    }
    $tree[] = [
      'id' => $id,
      'url' => $item->link->getUrlObject()->toString(),
      'title' => $item->link->getTitle(),
      'expanded' => $item->link->isExpanded(),
      'parent' => $item->link->getParent(),
      'weight' => $item->link->getWeight(),
      'items' => _stanford_basic_get_menu_tree_links($item->subtree),
    ];
  }
  uasort($tree, fn($a, $b) => $a['weight'] != $b['weight'] ? $a['weight'] <=> $b['weight'] : $a['title'] > $b['title']);
  return array_values($tree);
}
