<?php

/**
 * @file
 * Preprocess functions for the c-ShARP Subtheme.
 */

/**
 * Prepares variables for the html.html.twig template.
 */
function c_sharp_subtheme_preprocess_html(&$variables) {
  $variables['stanford_basic_path'] = \Drupal::service('extension.list.theme')->getPath('stanford_basic');
}

/**
 * Implements hook_theme_suggestions_HOOK_alter().
 */
function c_sharp_subtheme_theme_suggestions_block_alter(array &$suggestions, array $variables) {
  if (!empty($variables['elements']['#id']) && $variables['elements']['#id'] == 'c_sharp_subtheme_search') {
    $suggestions[] = 'block__stanford_basic_search';
  }
}

function c_sharp_subtheme_preprocess_paragraph__stanford_banner(&$variables) {
  $paragraph = $variables['paragraph'];

  // Add banner variant style class to card wrapper.
  $variables['attributes']['class'][] = $paragraph->getBehaviorSetting('react_paragraphs:banner_variant_info', 'banner_style');
}

/**
 * Implements hook_preprocess_page_title().
 */
function c_sharp_subtheme_preprocess_page_title(&$variables) {
  if (\Drupal::request()->getPathInfo() == '/search') {
    $variables['title']['#markup'] = 'Search Shared Facilities';
  }
}
